var List = {
	tv : [
		{
			name:'血色浪漫',
			tag:'china',
			time:'2004',
			douban:'http://movie.douban.com/subject/1931974/',
			poster:'../../images/life/movie/xueselangman.jpg',
			director:'钟跃民',
			star:''
		},
		{
			name:'大明王朝1566',
			tag:'china',
			time:'2007',
			douban:'http://movie.douban.com/subject/2210001/',
			poster:'../../images/life/movie/damingwangchao.jpg',
			director:'张黎 刘和平',
			star:''
		},
		{
			name:'贞观之治',
			tag:'china',
			time:'2006',
			douban:'http://movie.douban.com/subject/2155164/',
			poster:'../../images/life/movie/zhiguanzhizhi.jpg',
			director:'张建亚',
			star:''
		},
		{
			name:'走向共和',
			tag:'china',
			time:'2003',
			douban:'http://movie.douban.com/subject/1441794/',
			poster:'../../images/life/movie/zouxianggonghe.jpg',
			director:'张黎',
			star:''
		},
		{
			name:'潜伏',
			tag:'china',
			time:'2009',
			douban:'http://movie.douban.com/subject/3314870/',
			poster:'../../images/life/movie/qianfu.jpg',
			director:'姜伟 / 付玮',
			star:''
		},
		{
			name:'神雕侠侣',
			tag:'china',
			time:'1995',
			douban:'http://movie.douban.com/subject/1863947/',
			poster:'../../images/life/movie/shendiaoxialv.jpg',
			director:'李添胜',
			star:''
		},
		{
			name:'天龙八部',
			tag:'china',
			time:'1997',
			douban:'http://movie.douban.com/subject/1863941/',
			poster:'../../images/life/movie/tianlongbabu.jpg',
			director:'想我康敏素以美貌著称',
			star:''
		},
		{
			name:'我的团长我的团',
			tag:'china',
			time:'2009',
			douban:'http://movie.douban.com/subject/2997325/',
			poster:'../../images/life/movie/wodetuanzhang.jpg',
			director:'康洪雷',
			star:''
		},
		{
			name:'士兵突击',
			tag:'china',
			time:'2006',
			douban:'http://movie.douban.com/subject/2154096/',
			poster:'../../images/life/movie/shibingtuji.jpg',
			director:'康洪雷',
			star:''
		},
		{
			name:'三国演义',
			tag:'china',
			time:'1994',
			douban:'http://movie.douban.com/subject/1830528/',
			poster:'../../images/life/movie/sanguoyanyi.jpg',
			director:'古今多少事，都付谈笑中',
			star:''
		},
		{
			name:'红楼梦',
			tag:'china',
			time:'1987',
			douban:'http://movie.douban.com/subject/1864810/',
			poster:'../../images/life/movie/hongloumeng.jpg',
			director:'王扶林',
			star:''
		}
	],
	film : [
		{
			name:'马路天使',
			tag:'china',
			time:'1937',
			douban:'http://movie.douban.com/subject/1307708/',
			poster:'../../images/life/movie/film-china/malutianshi.jpg',
			director:'袁牧之',
			star:''
		},
		{
			name:'小城之春',
			tag:'china',
			time:'1948',
			douban:'http://movie.douban.com/subject/1323746/',
			poster:'../../images/life/movie/film-china/xiaochengzhichun.jpg',
			director:'费穆',
			star:''
		},
		{
			name:'芙蓉镇',
			tag:'china',
			time:'1986',
			douban:'http://movie.douban.com/subject/1297880/',
			poster:'../../images/life/movie/film-china/furongzhen.jpg',
			director:'谢晋',
			star:''
		},
		{
			name:'小武',
			tag:'china',
			time:'1987',
			douban:'http://movie.douban.com/subject/1864810/',
			poster:'../../images/life/movie/film-china/xiaowu.jpg',
			director:'贾樟柯',
			star:''
		},
		{
			name:'十七岁的单车',
			tag:'china',
			time:'2001',
			douban:'http://movie.douban.com/subject/1291847/',
			poster:'../../images/life/movie/film-china/shiqisuidedanche.jpg',
			director:'王小帅',
			star:''
		},
		{
			name:'颐和园',
			tag:'china',
			time:'2006',
			douban:'http://movie.douban.com/subject/1864810/',
			poster:'../../images/life/movie/film-china/yiheyuan.jpg',
			director:'娄烨',
			star:''
		},
		{
			name:'万箭穿心',
			tag:'china',
			time:'2012',
			douban:'http://movie.douban.com/subject/10537853/',
			poster:'../../images/life/movie/film-china/wanjianchuanxin.jpg',
			director:'王竞',
			star:''
		},
		{
			name:'蛤蛤怒斥香港女记者',
			tag:'china',
			time:'2001',
			douban:'http://movie.douban.com/subject/1864810/',
			poster:'../../images/life/movie/film-china/jiangzhuxi.jpg',
			director:'董特首',
			star:''
		}
	]
};